### PR TITLE
Added Unit Test for Motor Cruise Control Toggle Functionality

### PR DESCRIPTION
**Pull request by SparshK312**
This PR adds a unit test to check the motor cruise control toggle. It verifies that the cruise control starts off and turns on after simulating a button press with values [0] and [0xFF]. Let me know if any changes are needed.

### CODE REVIEW

**Comment by AussieSeaweed** [comment]
Very good. Now I think about it, we should also test trying to change the state again to see if the value also changes again, as expected. In other words, either "toggle" one more time or no longer press (for momentary switch) and make sure the values change again in the two test methods.

**Comment by SparshK312** [comment]
I added the checks for the OFF state when the array relay is no longer held, and the check for the OFF state when the cruise control is toggled off.

**Comment by AussieSeaweed** [comment]
@alexlewis9 @SparshK312 Good job guys.

Some comments:

1. The motor cruise control check didn't really work, but it was almost good. I fixed it to work.
  - Some fudging of test configurations was necessary.
  - To turn on and off using toggles, the switch read must be overridden as OFF (inactive), ON (active), OFF (active), ON (inactive), OFF (inactive).
2. I find comments to be ugly in general. I try to avoid it whenever I can.
3. When setting up, the contexts must be copied (e.g., with ``dataclasses.replace``) as the previous test case may have changed it.

**Review by AussieSeaweed — APPROVED** [review]

**Comment by SparshK312** [comment]
Got it, will keep in mind moving forward. Your changes look good, thank you for the modifications.

**Comment by alexlewis9** [comment]
Look good. Thanks.

**Pull request merged**
